version: "3.8"

services:

  app:
    build: ./app
    container_name: node-api

    ports:
      - "3000:3000"

    environment:
      - MONGO_URL=mongodb://mongodb:27017

    depends_on:
      - mongodb

  mongodb:
    image: mongo:8

    container_name: mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
